ALTER TABLE syncup.tasks

ADD COLUMN IF NOT EXISTS is_recurring BOOLEAN,
ADD COLUMN IF NOT EXISTS recurrence_str VARCHAR,
ADD COLUMN IF NOT EXISTS start_date TIMESTAMP,
ADD COLUMN IF NOT EXISTS end_date TIMESTAMP;



