CREATE TABLE syncup.user_types (
  id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR NOT NULL
);

CREATE TABLE syncup.users (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  full_name      VARCHAR NOT NULL,
  email          VARCHAR(255),
  role_type      INT NOT NULL REFERENCES syncup.user_types(id),
  cognito_sub    UUID NOT NULL,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TRIGGER user_updated_at
  BEFORE UPDATE ON syncup.users
  FOR EACH ROW
  EXECUTE FUNCTION set_updated_at();
