CREATE TABLE syncup.departments (
  id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name                 TEXT NOT NULL UNIQUE,
  parent_id BIGINT NULL
    REFERENCES syncup.departments(id)
    ON DELETE SET NULL,
  created_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at           TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_departments_parent ON syncup.departments(parent_id);

CREATE INDEX idx_departments_name_ci ON syncup.departments((lower(name)));

CREATE TRIGGER departments_updated_at
  BEFORE UPDATE ON syncup.departments
  FOR EACH ROW
  EXECUTE FUNCTION set_updated_at();
