spring:
  application:
    name: spm-orangle-backend
  datasource:
    url: ${QA_DB_URL:jdbc:postgresql://localhost:5432/qa_db}
    driver-class-name: ${QA_DB_DRIVER:org.postgresql.Driver}
    username: ${QA_DB_USERNAME:qa_user}
    password: ${QA_DB_PASSWORD:qa_password}
  jpa:
    database: POSTGRESQL
    open-in-view: false

aws:
  cognito:
    region: ${AWS_REGION:ap-southeast-1}
    app-client-id: ${AWS_COGNITO_APP_CLIENT_ID:}
    user-pool-id: ${AWS_COGNITO_USER_POOL_ID:}
  access-key-id: ${AWS_ACCESS_KEY_ID:}
  secret-access-key: ${AWS_SECRET_ACCESS_KEY:}

server:
  port: ${QA_SERVER_PORT:8080}

springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger
    enabled: true

logging:
  level:
    root: ${QA_LOG_LEVEL:INFO}

supabase:
  storage:
    url: https://qkoobjhbvvysowdogmak.storage.supabase.co/storage/v1/s3
    s3_aws_access_key_id: ${AWS_S3_ACCESS_KEY_ID}
    s3_aws_secret_access_key: ${AWS_S3_SECRET_ACCESS_KEY}
    region: ap-southeast-1
    bucket: syncup_bucket