spring:
  application:
    name: spm-orangle-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/localtestdb
    username: localtestuser
    password: localtestpassword
    hikari:
      maximum-pool-size: ${DB_POOL_SIZE:10}
      minimum-idle: ${DB_POOL_MIN:2}
  jpa:
    database: POSTGRESQL
    open-in-view: false
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:admin}
    password: ${RABBITMQ_PASSWORD:admin}
    virtual-host: ${RABBITMQ_VHOST:/}
    listener:
      simple:
        acknowledge-mode: auto
        prefetch: 1
        retry:
          enabled: true
          initial-interval: 1000
          max-attempts: 3
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:your-email@gmail.com}
    password: ${MAIL_PASSWORD:your-app-password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    from: ${MAIL_FROM:noreply@spmorangle.com}

aws:
  cognito:
    region: ${AWS_REGION:ap-southeast-1}
    app-client-id: ${AWS_COGNITO_APP_CLIENT_ID:}
    user-pool-id: ${AWS_COGNITO_PUBLIC_USER_POOL_ID:}
  access-key-id: ${AWS_ACCESS_KEY_ID:}
  secret-access-key: ${AWS_SECRET_ACCESS_KEY:}

server:
  port: ${DEV_SERVER_PORT:8080}

springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger
    enabled: true

app:
  frontend:
    base-url: ${FRONTEND_BASE_URL:http://localhost:3000}
  comments:
    max-length: ${COMMENTS_MAX_LENGTH:2000}
    allow-mentions: ${COMMENTS_ALLOW_MENTIONS:true}
    require-moderation: ${COMMENTS_REQUIRE_MODERATION:false}

supabase:
  storage:
    url: https://qkoobjhbvvysowdogmak.storage.supabase.co/storage/v1/s3
    s3_aws_access_key_id: ${AWS_S3_ACCESS_KEY_ID}
    s3_aws_secret_access_key: ${AWS_S3_SECRET_ACCESS_KEY}
    region: ap-southeast-1
    bucket: syncup_bucket

logging:
  level:
    org.springframework.amqp: DEBUG
    com.spmorangle.crm.notification: DEBUG
    com.spmorangle.crm.taskmanagement.service: DEBUG