spring:
  application:
    name: spm-orangle-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/localtestdb
    username: localtestuser
    password: localtestpassword
    hikari:
      maximum-pool-size: ${DB_POOL_SIZE:10}
      minimum-idle: ${DB_POOL_MIN:2}
  jpa:
    database: POSTGRESQL
    open-in-view: false

aws:
  cognito:
    region: ${AWS_REGION:ap-southeast-1}
    app-client-id: ${AWS_COGNITO_APP_CLIENT_ID:}
    user-pool-id: ${AWS_COGNITO_PUBLIC_USER_POOL_ID:}
  access-key-id: ${AWS_ACCESS_KEY_ID:}
  secret-access-key: ${AWS_SECRET_ACCESS_KEY:}

server:
  port: ${DEV_SERVER_PORT:8080}

springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger
    enabled: true

<<<<<<< HEAD
app:
  features:
    notifications:
      enabled: ${NOTIFICATIONS_ENABLED:false}  # Toggle when notification service is ready
    permissions:
      enabled: ${PERMISSIONS_ENABLED:false}  # Toggle when permission service is ready
  comments:
    max-length: ${COMMENTS_MAX_LENGTH:2000}
    allow-mentions: ${COMMENTS_ALLOW_MENTIONS:true}
    require-moderation: ${COMMENTS_REQUIRE_MODERATION:false}
=======
supabase:
  storage:
    url: https://qkoobjhbvvysowdogmak.storage.supabase.co/storage/v1/s3
    s3_aws_access_key_id: ${AWS_S3_ACCESS_KEY_ID}
    s3_aws_secret_access_key: ${AWS_S3_SECRET_ACCESS_KEY}
    region: ap-southeast-1
    bucket: syncup_bucket
>>>>>>> 3389ff7 (complete file service)
