spring:
  application:
    name: spm-orangle-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/localtestdb
    username: localtestuser
    password: localtestpassword
    hikari:
      maximum-pool-size: ${DB_POOL_SIZE:10}
      minimum-idle: ${DB_POOL_MIN:2}
  jpa:
    database: POSTGRESQL
    open-in-view: false

aws:
  cognito:
    region: ${AWS_REGION:ap-southeast-1}
    app-client-id: ${AWS_COGNITO_APP_CLIENT_ID:}
    user-pool-id: ${AWS_COGNITO_USER_POOL_ID:}
  access-key-id: ${AWS_ACCESS_KEY_ID:}
  secret-access-key: ${AWS_SECRET_ACCESS_KEY:}

server:
  port: ${DEV_SERVER_PORT:8080}

springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger
    enabled: true