spring:
  application:
    name: spm-orangle-backend
  datasource:
    url: ${DEV_DB_URL:jdbc:h2:mem:devdb}
    driver-class-name: ${DEV_DB_DRIVER:org.h2.Driver}
    username: ${DEV_DB_USERNAME:sa}
    password: ${DEV_DB_PASSWORD:}
  jpa:
    database: POSTGRESQL
    open-in-view: false

aws:
  cognito:
    region: ${AWS_REGION:ap-southeast-1}
    app-client-id: ${AWS_COGNITO_APP_CLIENT_ID:}
    user-pool-id: ${AWS_COGNITO_USER_POOL_ID:}
  access-key-id: ${AWS_ACCESS_KEY_ID:}
  secret-access-key: ${AWS_SECRET_ACCESS_KEY:}

server:
  port: ${DEV_SERVER_PORT:8080}

springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger
    enabled: true

logging:
  level:
    root: ${DEV_LOG_LEVEL:DEBUG}