spring:
  application:
    name: spm-orangle-backend
  datasource:
    url: ${PROD_DB_URL:jdbc:postgresql://prod-server:5432/prod_db}
    driver-class-name: ${PROD_DB_DRIVER:org.postgresql.Driver}
    username: ${PROD_DB_USERNAME:prod_user}
    password: ${PROD_DB_PASSWORD:prod_password}
  jpa:
    database: POSTGRESQL
    open-in-view: false

aws:
  cognito:
    region: ${AWS_REGION:ap-southeast-1}
    app-client-id: ${AWS_COGNITO_APP_CLIENT_ID:}
    user-pool-id: ${AWS_COGNITO_USER_POOL_ID:}
  access-key-id: ${AWS_ACCESS_KEY_ID:}
  secret-access-key: ${AWS_SECRET_ACCESS_KEY:}

server:
  port: ${PROD_SERVER_PORT:8080}

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

logging:
  level:
    root: ${PROD_LOG_LEVEL:WARN}

supabase:
  storage:
    url: https://qkoobjhbvvysowdogmak.storage.supabase.co/storage/v1/s3
    s3_aws_access_key_id: ${AWS_S3_ACCESS_KEY_ID}
    s3_aws_secret_access_key: ${AWS_S3_SECRET_ACCESS_KEY}
    region: ap-southeast-1
    bucket: syncup_bucket