spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: ${DEV_DB_URL:jdbc:h2:mem:devdb}
    driver-class-name: ${DEV_DB_DRIVER:org.h2.Driver}
    username: ${DEV_DB_USERNAME:sa}
    password: ${DEV_DB_PASSWORD:}
  jpa:
    hibernate:
      ddl-auto: ${DEV_JPA_DDL_AUTO:update}
    show-sql: ${DEV_JPA_SHOW_SQL:true}

server:
  port: ${DEV_SERVER_PORT:8080}

logging:
  level:
    root: ${DEV_LOG_LEVEL:DEBUG}