name: Backend Spring Boot App CI

permissions:
  contents: read
  issues: write
  pull-requests: write

on:
  pull_request:
    branches:
      - main
  push:
    paths:
      - "backend/spmorangle/**"
      - ".github/workflows/backend-ci.yml"

env:
  JAVA_VERSION: 21

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: test
          POSTGRES_DB: spmorangle_test
          POSTGRES_USER: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: "temurin"
          cache: maven

      - name: Compile application
        working-directory: ./backend/spmorangle
        run: mvn compile

      - name: Run tests
        working-directory: ./backend/spmorangle
        run: mvn test -Dspring.profiles.active=test

      - name: Package application
        working-directory: ./backend/spmorangle
        run: mvn package -DskipTests
  